(in-package :kunabi)

(defun argv ()
  (or
   #+clisp (ext:argv)
   #+sbcl sb-ext:*posix-argv*
   #+abcl ext:*command-line-argument-list*
   #+clozure (ccl::command-line-arguments)
   #+gcl si:*command-args*
   #+ecl (loop for i from 0 below (si:argc) collect (si:argv i))
   #+cmu extensions:*command-line-strings*
   #+allegro (sys:command-line-arguments)
   #+lispworks sys:*line-arguments-list*
   nil))

;; (let ((verb (or (nth 1 args) nil))
;; 	(a (or (nth 2 args) nil))
;; 	(b (or (nth 3 args) nil))
;; 	(c (or (nth 4 args) nil)))

#+sbcl
(defun sbcl-entry()
  (handler-case (main)
    (sb-sys:interactive-interrupt ()
      (sb-ext:quit))))

(defun usage ()
  (print "a - cloudtrail-report-async")
  (print "b - bench-vpc-flows-report-sync arg")
  (print "lc - get-unique-conversation")
  (print "lec - get-errorcode-list")
  (print "lev - get-event-list")
  (print "lip - get-sourceips-list")
  (print "ln - get-name-list")
  (print "lva - get-vpc-action-list")
  (print "lvd - get-vpc-date-list")
  (print "lvda - get-vpc-dstaddr-list")
  (print "lvdp - get-vpc-srcport-list")
  (print "lvi - get-vpc-interface-id-list")
  (print "lvp - get-vpc-protocols-list")
  (print "lvpc - list-all-vpc")
  (print "lvs - get-vpc-status-list")
  (print "lvsa - get-vpc-srcaddr-list")
  (print "lvsp - get-vpc-srcport-list")
  (print "r - run-bench")
  (print "s - cloudtrail-report-sync arg")
  (print "sa - find-by-srcaddr arg")
  (print "sd - ct-get-by-date arg")
  (print "sec - get-by-errorcode arg")
  (print "seca - ct-get-all-errors")
  (print "sev - get-by-event arg")
  (print "sin - get-useridentity-by-name arg")
  (print "sip - get-by-sourceip arg")
  (print "sn - get-by-name arg")
  (print "sp - find-by-srcport arg")
  (print "st - get-stats")
  (print "va - vpc-flows-report-async arg beta")
  (print "vs - vpc-flows-report-sync arg")
  (print "vsp - vpc-search-by-srcport port")
  (print "vdp - vpc-search-by-dstport port")
  (print "vsi - vpc-search-by-srcip port")
  (print "vdi - vpc-search-by-dstip port")
)

(defun process-args (args)
  ;;(in-package :cl-user)
  ;;(define-alien-variable "gencgc-oldest-gen-to-gc" (unsigned 8))(setf gencgc-oldest-gen-to-gc 1)
  ;;(setf gencgc-oldest-gen-to-gc 1)
  ;;(in-package :kunabi)
  (init-manardb)

  (let (
	(verb (nth 1 args))
	(alpha (nth 2 args))
	(beta (nth 3 args))
	)
    ;;(format t "main:~A verb:~A alpha:~A beta:~A" (nth 0 args) verb alpha beta)
    (cond
      ((equal "a" verb)(time (cloudtrail-report-async alpha beta)))
      ((equal "b" verb)(time (bench-vpc-flows-report-sync alpha)))
      ((equal "lc" verb)(time (get-unique-conversation)))
      ((equal "lec" verb)(time (get-errorcode-list)))
      ((equal "lev" verb)(time (get-event-list)))
      ((equal "lip" verb)(time (get-sourceips-list)))
      ((equal "ln" verb)(time (get-name-list)))
      ((equal "lva" verb)(get-vpc-action-list))
      ((equal "lvd" verb)(get-vpc-date-list))
      ((equal "lvda" verb)(get-vpc-dstaddr-list))
      ((equal "lvdp" verb)(get-vpc-srcport-list))
      ((equal "lvi" verb)(get-vpc-interface-id-list))
      ((equal "lvip" verb)(get-by-ip alpha))
      ((equal "lvip2" verb)(get-by-ip2 alpha))
      ((equal "lvp" verb)(get-vpc-protocols-list))
      ((equal "lvpc" verb)(time (list-all-vpc)))
      ((equal "lvs" verb)(get-vpc-status-list))
      ((equal "lvsa" verb)(get-vpc-srcaddr-list))
      ((equal "lvsp" verb)(get-vpc-srcport-list))
      ((equal "r" verb)(time (run-bench)))
      ((equal "s" verb)(time (cloudtrail-report-sync alpha)))
      ((equal "sa" verb)(find-by-srcaddr alpha))
      ((equal "sd" verb)(time (get-by-date alpha)))
      ((equal "sec" verb)(time (ct-get-by-errorcode alpha)))
      ((equal "seca" verb)(time (ct-get-all-errors)))
      ((equal "sem" verb)(time (ct-get-by-errormessage alpha)))
      ((equal "ses" verb)(time (ct-get-by-event-source alpha)))
      ((equal "sev" verb)(time (ct-get-by-eventName alpha)))
      ((equal "sin" verb)(time (get-useridentity-by-name alpha)))
      ((equal "sip" verb)(time (ct-get-by-sourceipaddress alpha)))
      ((equal "sn" verb)(time (ct-get-by-name alpha)))
      ((equal "sp" verb)(find-by-srcport alpha))
      ((equal "st" verb)(get-stats))
      ((equal "va" verb)(time (vpc-flows-report-async alpha beta)))
      ((equal "vda" verb)(time (vpc-search-by-dstaddr alpha)))
      ((equal "vdp" verb)(time (vpc-search-by-dstport alpha)))
      ((equal "vs" verb)(time (vpc-flows-report-sync alpha)))
      ((equal "vsa" verb)(time (vpc-search-by-srcaddr alpha)))
      ((equal "vsp" verb)(time (vpc-search-by-srcport alpha)))
      ((equal "ls" verb)(time (sync-from-s3 alpha)))
      ((equal "ctf" verb)(time (get-ct-files)))
      (t (progn
	   (usage))))
  (manardb:close-all-mmaps)))

(defun main ()
  (init-manardb)
  #+sbcl
  (handler-case (process-args (argv))
    (sb-sys:interactive-interrupt ()
      (sb-ext:quit)))
  #-sbcl
  (process-args (argv)))

#+allegro
(in-package :cl-user)

#+allegro
(defun main (&rest args)
  (kunabi::process-args args))
